### ISSUE TITLE
[BUG] error

### ISSUE THREAD

**Issue by eseeseuwawa** [joker-ware/JokerCord#34]
Traceback (most recent call last):
  File "C:\Users\marcw\Downloads\JokerCord-master\JokerCord-master\joker.py", line 213, in <module>
    app.run(port="5555", debug = False)
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\app.py", line 985, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\cli.py", line 670, in show_server_banner
    click.echo(message)
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\click\utils.py", line 218, in echo
    file = _default_text_stdout()
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Users\marcw\AppData\Local\Programs\Python\Python35\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno
Why isnt the port working, I figured it had something t do wih this error.

**Comment by joker-ware** [comment]
Please update your python version and the libraries.
