### ISSUE TITLE
cannot connect to host discordapp.com:443

### ISSUE THREAD

**Issue by GoldenAdrien** [joker-ware/JokerCord#4]
hi whenever i run joker.py it gives me this: "Cannot connect to host discordapp.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)]
Something went wrong with the token. If this is the first time you use this bot, please go to http://localhost:5555 and edit your preferences."; even though i already put in my token correctly several times.  do you have any idea what is going on?

**Comment by joker-ware** [comment]
Hello, as I could read on internet, this is probably an error caused by MacOS's python distribution. A quick solution would be to navigate to your Applications folder and do this:
Basically navigate to your Applications/Python 3.7/ folder and double click the Install Certificates.command.

**Comment by joker-ware** [comment]
Have you solved the issue?

**Comment by GoldenAdrien** [comment]
i just saw your reply i will try that now, although i think i only have python 3.6 installed

**Comment by joker-ware** [comment]
Yes, I think that's the problem, Mac OS comes with 3.6 by default, and it's certificates are kind of broken. You'd better install 3.7 or install the certificates (I'd suggest installing 3.7)

**Comment by GoldenAdrien** [comment]
upon further inspection, i don't even have a python 3.6 folder in my applications folder

**Comment by joker-ware** [comment]
Well then, try installing 3.7

**Comment by GoldenAdrien** [comment]
I am now installing python 3.7 since it seems like there is no install certificates command in python 3.6

**Comment by GoldenAdrien** [comment]
now it won't let me run the install certificates command due to insufficient permissions and i have no idea how to fix that

**Comment by joker-ware** [comment]
Try doing it with sudo. Just type ```bash
sudo
``` before the command

**Comment by GoldenAdrien** [comment]
it won't let me edit the command

**Comment by GoldenAdrien** [comment]
i am sorry if i am sounding like an idiot i am still getting used to python

**Comment by joker-ware** [comment]
It's no problem, not everybody has to know Python. How are you typing the command?

**Comment by GoldenAdrien** [comment]
pip3 install --upgrade certifi --user

**Comment by joker-ware** [comment]
Can you try this?:
```bash
python3 -m pip install --upgrade certifi --trusted-host pypi.org --trusted-host files.pythonhosted.org
```

**Comment by GoldenAdrien** [comment]
I will

**Comment by GoldenAdrien** [comment]
ok i did that but now it won't let me install PIL and it says:
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)

**Comment by joker-ware** [comment]
Oh yes. You can try to install it with "pillow" instead of "PIL"

**Comment by GoldenAdrien** [comment]
oh thanks!

**Comment by GoldenAdrien** [comment]
so that worked but now when i run the command python3 joker.py, it gives me this:
 * Serving Flask app "joker" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)
Cannot connect to host discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]
Something went wrong with the token. If this is the first time you use this bot, please go to http://localhost:5555 and edit your preferences.

even though i already did that stuff and got the correct token

**Comment by joker-ware** [comment]
You still have an SSL certificate failure. Can you try to navigate again to your /Applications/Python3.6 folder and see if you have a install certificates file?

**Comment by GoldenAdrien** [comment]
oh i have upgrade to python 3.7 but i will still try

**Comment by GoldenAdrien** [comment]
ok whenever i run the install certificates command file it gives me this:
 -- pip install --upgrade certifi
Collecting certifi
  Using cached https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Installing collected packages: certifi
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<stdin>", line 44, in <module>
  File "<stdin>", line 25, in main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7', '-E', '-s', '-m', 'pip', 'install', '--upgrade', 'certifi']' returned non-zero exit status 1.

**Comment by joker-ware** [comment]
Try running it with ```sudo```
Just put it behind the entire command.

**Comment by GoldenAdrien** [comment]
like do:
sudo (FILE PATH)?

**Comment by joker-ware** [comment]
Yes.

**Comment by GoldenAdrien** [comment]
do i use the administrator password or the second account password? I am on my computer's second account

**Comment by joker-ware** [comment]
Your second account password. That is, supposing that account has admin privileges

**Comment by GoldenAdrien** [comment]
If it does not have admin privileges, do I use the administrator password then?

**Comment by joker-ware** [comment]
Yep

**Comment by GoldenAdrien** [comment]
neither of the passwords are working.  Idk if it is because it isn't entering the password since it doesn't show that the password is being put in or if it is something else

**Comment by joker-ware** [comment]
It's normal, the password must not be shown, neither * or any type of symbol. Check both passwords

**Comment by GoldenAdrien** [comment]
neither are working for me

**Comment by GoldenAdrien** [comment]
i am going to try to make the account an admin

**Comment by GoldenAdrien** [comment]
It works!  Out of curiosity how do i make it focus on only one server?

**Comment by GoldenAdrien** [comment]
never mind i got it to work! thanks for all of your help!

**Comment by joker-ware** [comment]
Go to the webpage->settings->disable all servers except the one you want

**Comment by GoldenAdrien** [comment]
which webpage?

**Comment by joker-ware** [comment]
http://localhost:5555

**Comment by GoldenAdrien** [comment]
You might want to change the title of that section of the settings from 'Enable/Disable Guilds' to 'Enable/Disable Servers'

**Comment by joker-ware** [comment]
Yep. I'm considering on moving that section to the main page instead of being hidden inside Settings

**Comment by GoldenAdrien** [comment]
Ahhh ok!

**Comment by GoldenAdrien** [comment]
Thanks for the help!  I really appreciate it!

**Comment by joker-ware** [comment]
No problem! Remember to give me a star to support my work :D

**Comment by JulotCraft** [comment]
I'm sorry but I read the issue and I don't understand (I have the same thing)
