### ISSUE TITLE
TypeError: argument of type 'MemoryError' is not iterable

### ISSUE THREAD

**Issue by PTiffania** [joker-ware/JokerCord#43]
Thats my problem what i can do?

**Comment by joker-ware** [comment]
Can you elaborate more on the problem? If possible, please send a screenshot of the error.

**Comment by manobig13** [comment]
File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\gateway.py", line 345, in received_message
    msg = msg.decode('utf-8')
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Rafael\Desktop\PokeCord\joker.py", line 37, in loop_in_thread
    loop.run_until_complete(startClient())
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Users\Rafael\Desktop\PokeCord\joker.py", line 32, in startClient
    if("Improper token" in e):
TypeError: argument of type 'MemoryError' is not iterable

**Comment by manobig13** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Rafael\Desktop\PokeCord\joker.py", line 29, in startClient
    await bot_thread.client.start(pr_l["token"], bot=False)
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\gateway.py", line 345, in received_message
    msg = msg.decode('utf-8')
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Rafael\Desktop\PokeCord\joker.py", line 37, in loop_in_thread
    loop.run_until_complete(startClient())
  File "C:\Users\Rafael\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Users\Rafael\Desktop\PokeCord\joker.py", line 32, in startClient
    if("Improper token" in e):
TypeError: argument of type 'MemoryError' is not iterable

**Comment by manobig13** [comment]
i dont know it works for some time and gives me that error after some time of working

**Comment by joker-ware** [comment]
It does seem to be a Discord. py problem. When exactly did that occur? What was the bot doing? Is the server you are in large?

**Comment by manobig13** [comment]
no only 3 ppl

**Comment by joker-ware** [comment]
What are your specs? What is your OS? Your RAM and available space on the disk?

**Comment by PTiffania** [comment]
ryzen r71700 gtx10606gb 16ram

**Comment by PTiffania** [comment]
windows 10

**Comment by joker-ware** [comment]
Are you running low on space?

**Comment by PTiffania** [comment]
i have ssd with more 90gb and HD with more 700gb free space

**Comment by joker-ware** [comment]
Does that message appear everytime you start the bot?

**Comment by PTiffania** [comment]
no after some time

**Comment by PTiffania** [comment]
like 2 min

**Comment by PTiffania** [comment]
he works like 2 min catch and spam but after 2-5 min he stops and gives error

**Comment by PTiffania** [comment]
![Capturar](https://user-images.githubusercontent.com/24780496/72672161-2c1a4280-3a4e-11ea-9209-f19571cfbd16.PNG)

**Comment by joker-ware** [comment]
It is a problem that I cannot solve myself. But I'm trying to approach the error as much as I can. Has any weird message been sent lately on that server? Like, a message with weird Non-unicode symbols or a very large message?

**Comment by PTiffania** [comment]
no

**Comment by PTiffania** [comment]
i have 20 discord Enable but not all have pokecord

**Comment by PTiffania** [comment]
maybe i turn off all

**Comment by joker-ware** [comment]
I would as a last resort recommend to you install Python 3.6 or 3.7 to check compatibility, or install the 64 bit version of your Python and update it to the latest version

**Comment by joker-ware** [comment]
What do you mean 20 discord?

**Comment by PTiffania** [comment]
enable/disable guilds

**Comment by PTiffania** [comment]
you have discord for screenshare?

**Comment by joker-ware** [comment]
It may be the cause. Those are too many servers at a time (but even your system should handle them) can you select less of them and check if the problem persists?

**Comment by PTiffania** [comment]
yes only 1 enable guild and TypeError: argument of type 'MemoryError' is not iterable
127.0.0.1 - - [19/Jan/2020 00:01:58] "GET /home HTTP/1.1" 200 -

**Comment by joker-ware** [comment]
I can help you on discord but tomorrow.SteeW#8629

**Comment by joker-ware** [comment]
Also, are you running this from your main account? Please use an alt. And it should even fix the memory error

**Comment by PTiffania** [comment]
yes is the main

**Comment by PTiffania** [comment]
why alt i want pokemons in this acc can you explain why alt?

**Comment by joker-ware** [comment]
You can always trade yourself the Pokemon's on the alternate account to the main one. The reason to use an alt is because spamming continuously can lead you to a discord ban. It is stated on the readme. But please, use an alt and trade the Pokemon's to your main when needed.
