### ISSUE TITLE
[BUG]the list of servers appears but no spam or capture works

### ISSUE THREAD

**Issue by rafaelconcept** [joker-ware/JokerCord#46]
i am receiving the message on the terminal

 * Serving Flask app "joker" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Jan/2020 00:44:07] "GET / HTTP/1.1" 200 -
'animated'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\JokerCord-master\joker.py", line 29, in startClient
    await bot_thread.client.start(pr_l["token"], bot=False)
  File "C:\python37\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\python37\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\python37\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\python37\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\python37\lib\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\python37\lib\site-packages\discord\state.py", line 407, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\JokerCord-master\joker.py", line 37, in loop_in_thread
    loop.run_until_complete(startClient())
  File "C:\python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\JokerCord-master\joker.py", line 32, in startClient
    if("Improper token" in e):
TypeError: argument of type 'KeyError' is not iterable

![Screenshot_48](https://user-images.githubusercontent.com/43880669/73149232-07057f80-409f-11ea-8ada-1ee780c91ed3.png)

how can I solve?

**Comment by joker-ware** [comment]
Hello, that is a discord.py error, it should be fixed in the latest release, please update ir by opening the console and typing:
```pip3 install discord.py```

**Comment by rafaelconcept** [comment]
I found that my connection was in trouble, so I decided to run on EC2 aws and it's working perfectly <3 How do I make it work on more than one channel on the same server?

**Comment by joker-ware** [comment]
Do you mean spam in multiple channels? Sorry, not possible for now :(

**Comment by rafaelconcept** [comment]
then it is already as a suggestion for the next update :D

**Comment by joker-ware** [comment]
Perfect! Already working on it.
