### ISSUE TITLE
Joker Cord Key error

### ISSUE THREAD

**Issue by Generic-Name123** [joker-ware/JokerCord#52]
I am constantly getting the following message constantly when trying to load up the bot. I imagine it has something to do with why I am not seeing my servers on the web Interface

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\FPC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "X:\XXXXX\XXXXX\Downloads\JokerCord-master\JokerCord-master\bot_thread.py", line 143, in on_message
    if (message.author.id != client.user.id and ev == 1 and (guild_list[str(message.guild.id)][0] == "True")): #and "A wild" in message.content):
KeyError: '319897695122882560'

Another thing I will say is whenever loading after a reboot or just loading up for the first time, It tends to take a while to actually start up. This may just be the code loading up and may not be serious issue however I just thought I'd ask and since I have a 6 core processer that rarely goes above 50% usage.

Thank you very much for this bot though and I think you're a doing a great job, keep at it.

**Comment by joker-ware** [comment]
Thanks for the feedback. Some users have been having this same issue , but I don't have a solution yet. However, it happens only on windows and for some users. Can you first tell me if you have administrator permissions? Can you try running cmd as Admin, navigate to JokerCord's directory (ex.: cd C:\blah\jokercord) and run it with ```python3 joker.py``` (or just ```python```) and tell me if that worked? I do not have a windows machine so as you can understand it is very hard for me to debug this problem. Any help would be appreciated.

**Comment by Generic-Name123** [comment]
Hello, I opened CMD as administrator and ran joker.py but I still got key errors and I also noticed another error for line 270:
File "C:\XXXXXX\XXXX\XXXXX\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)

**Comment by joker-ware** [comment]
Hello, what is the exact error? The one you sent is incomplete.

**Comment by Generic-Name123** [comment]
It just loops the following error with different KeyErrors each time until I close the program.

 Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\FPC\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\FPC\Downloads\JokerCord-master\JokerCord-master\bot_thread.py", line 143, in on_message
    if (message.author.id != client.user.id and ev == 1 and (guild_list[str(message.guild.id)][0] == "True")): #and "A wild" in message.content):
KeyError: '382316968394620938'

**Comment by MantisGalaxy** [comment]
I have the same issue. I don't have any solution

**Comment by joker-ware** [comment]
I have this bug in my priority list. I think I have a fix for it.

**Comment by MantisGalaxy** [comment]
I sent a screenshot in my issue ticket

**Comment by joker-ware** [comment]
I believe I've found the problem

**Comment by joker-ware** [comment]
@MantisGalaxy would you be able to contact me on discord? SteeW#8629

**Comment by MantisGalaxy** [comment]
Yes, I'm MantisFan#6053

**Comment by joker-ware** [comment]
Discord gives me an error whem trying to add you, can you try to add me? Or change your preferences so you are able to receive friend requests

**Comment by MantisGalaxy** [comment]
I've added you in Discord

**Comment by riesz01** [comment]
is there any solution for this yet?
